apiVersion: v1
kind: Secret
metadata:
  name: junkyard-credentials
  namespace: gyopart  # change to gyopart-dev for dev
type: Opaque
stringData:
  JUNKYARD_USER: gyopart_dev
  JUNKYARD_PASSWORD: your-password-here
  ADMIN_API_KEY: your-admin-key-here
