apiVersion: v1
kind: Secret
metadata:
  name: junkyard-credentials
  namespace: gyopart  # change to gyopart-dev for dev
type: Opaque
stringData:
  JUNKYARD_USER: gyopart
  JUNKYARD_PASSWORD: your-password-here
