apiVersion: v1
kind: Secret
metadata:
  name: parts-interchange-credentials
  namespace: gyopart  # change to gyopart-dev for dev
type: Opaque
stringData:
  PARTS_USER: gyopart_dev
  PARTS_PASSWORD: your-password-here
