# FROM ubuntu:22.04

# COPY geckodriver.tar.gz /opt/
# COPY firefox-119.0.tar.bz2 /opt/

# RUN apt-get update && apt-get install -y bzip2 libgtk-3-common libasound2 libdbus-glib-1-2 sudo

# RUN cd /opt && tar -xvf geckodriver.tar.gz && tar -xvf firefox-119.0.tar.bz2 && ln -s /opt/geckodriver /usr/local/bin/geckodriver && ln -s /opt/firefox/firefox /usr/local/bin/firefox

# RUN adduser --disabled-password --gecos '' docker &&\
# #  add-apt-repository ppa:mozillateam/ppa &&\
# #  echo '\
# #     Package: *\
# #     Pin: release o=LP-PPA-mozillateam\
# #     Pin-Priority: 1001\
# #     ' | sudo tee /etc/apt/preferences.d/mozilla-firefox &&\
#  adduser docker sudo &&\
#  echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
# #  mkdir -p /opt/scraper
# # RUN cd /usr/local/bin && tar -xvf geckodriver.tar.gz

# USER docker

# RUN sudo apt-get update && sudo apt install -y firefox

# ENV PATH="${PATH}:/home/docker/.local/bin"


FROM  fedora

RUN dnf -y update
RUN dnf -y install firefox